### ISSUE TITLE
Click on enter button it comes out of the the editing mode

### ISSUE THREAD

**Issue by solkararif** [qontu/ngx-inline-editor#105] opened 2017-10-27 12:15 UTC
When I click enter in the inline-editor it comes out of the editing mode instead of going to a new line
How can input value in a new line

**Comment by xxxtonixxx** [comment] 2017-10-30 11:00
Hi @solkararif, I closed this issue as duplicate of https://github.com/qontu/ngx-inline-editor/issues/93

Follow that issue instead! :wink:

**Closed** 2017-10-30 11:01 UTC
Labels: duplicate
